apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dotnet-github-actions-artifactory-100625xxx 
  janus-idp.io/tekton: dotnet-github-actions-artifactory-100625xxx
  backstage.io/kubernetes-id: dotnet-github-actions-artifactory-100625xxx
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dotnet-github-actions-artifactory-100625xxx
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml