apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-github-actions-artifactory-100625xxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-github-actions-artifactory-100625xxx 
  name: dotnet-github-actions-artifactory-100625xxx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet-github-actions-artifactory-100625xxx 
